## 1번 문제

adult.csv파일을 읽은 후에 null value값이 존재하는 column들을 확인하시오.

## 1번 문제 답안



In [ ]:
import pandas as pd
import numpy as np

adult_df = pd.read_csv('https://raw.githubusercontent.com/EugeneYoo/practice_file/main/adult.csv')

# 실습 자료에서 사용한 다른 방법도 가능합니다
print(adult_df.isnull().sum(axis=0)) 

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capitalGain          0
capitalLoss          0
hoursPerWeek         0
nativeCountry      583
income               0
dtype: int64


## 2번 문제

adult dataframe에 존재하는 `'workclass'` column의 missing value를 most frequent value inplacing(Hot Deck Imputation)기법을 활용하여 처리하시오.

## 2번 문제 답안

In [ ]:
import pandas as pd
adult_df = pd.read_csv('https://raw.githubusercontent.com/EugeneYoo/practice_file/main/adult.csv')

#데이터셋 컬럼 확인
print(adult_df['workclass'].value_counts(dropna=False))


#최빈값 저장
most_freq = adult_df['workclass'].value_counts(dropna=True).idxmax()
print('\n')
print("most freq value:", most_freq)
print('\n\n')

#최빈값으로 null 값 대체
adult_df['workclass'].fillna(most_freq, inplace = True)

#대체된 결과 확인
print(adult_df['workclass'].value_counts())

Private             22696
Self-emp-not-inc     2541
Local-gov            2093
NaN                  1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: workclass, dtype: int64


most freq value: Private



Private             24532
Self-emp-not-inc     2541
Local-gov            2093
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: workclass, dtype: int64


## 3번 문제

adult dataframe에 존재하는 `'nativeCountry'` column의 missing value를 Missing Value Deletion(row)기법을 활용하여 처리하시오.

## 3번 문제 답안

In [ ]:
import pandas as pd

adult_df = pd.read_csv('https://raw.githubusercontent.com/EugeneYoo/practice_file/main/adult.csv')

print("Before deletion: ", len(adult_df))

#Missing Value Deletion, row delte이므로 axis = 0
adult_df.dropna(subset=['nativeCountry'], how = 'any', axis = 0, inplace=True)

print("After deletion: ", len(adult_df))

Before deletion:  32561
After deletion:  31978


## 4번 문제

adult dataframe의 각 column별 데이터 타입을 확인하고 income column의 데이터 타입을 object에서 bool(50K 이하이면 False, 50K 초과이면 True)로 변경하시오.

## 4번 문제 답안

### 데이터 읽어오기

In [ ]:
import pandas as pd

adult_df = pd.read_csv('https://raw.githubusercontent.com/EugeneYoo/practice_file/main/adult.csv')

### 데이터 타입 확인


In [ ]:
adult_df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capitalGain        int64
capitalLoss        int64
hoursPerWeek       int64
nativeCountry     object
income            object
dtype: object

### 데이터 확인

In [ ]:
adult_df.head()

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capitalGain  capitalLoss  hoursPerWeek  nativeCountry income  
0         2174            0            40  United-States  <=50K  
1            0            0            13  United-States  <=50K  
2            0            0            40  United-States  <=50K  
3            0            0            40  United-States  <=50K  
4            0            0            40           Cuba  <=50K

In [ ]:
adult_df['income'].unique()

array(['<=50K', '>50K'], dtype=object)

In [ ]:
adult_df['income'].value_counts()

<=50K    24720
>50K      7841
Name: income, dtype: int64

### 데이터 변환

데이터를 대체할 수 있는 코드 아무거나 가능.

참조 코드

```python

# 답안에서는 pandas의 assign 사용

# 데이터 프레임 생성
df = pd.DataFrame(index=['row1','row2','row3'],data={'col1':[1,2,3]})
print(df)
>>
      col1
row1     1
row2     2
row3     3

# col1 기반으로 assign을 통해 col2 생성
print(df.assign(col2=lambda x : x.col1+2))
>>
      col1  col2
row1     1     3
row2     2     4
row3     3     5

# assign은 중복되는 column이 존재하면 갚을 덮어 씌움
print(df.assign(col1=[0,0,0]))
>>
      col1
row1     0
row2     0
row3     0
```

In [ ]:
adult_df = adult_df.assign(income=lambda x: (adult_df['income'] != '<=50K'))

#아래 주석 코드는 참조용
#adult_df = adult_df.assign(income = adult_df['income'] != '<=50K')

### 변환된 데이터 확인

In [ ]:
adult_df[['income']].head()

income
0   False
1   False
2   False
3   False
4   False

In [ ]:
adult_df['income'].unique()

array([False,  True])

In [ ]:
# income 의 type이 ojbect -> bool 로 변경됨
adult_df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capitalGain        int64
capitalLoss        int64
hoursPerWeek       int64
nativeCountry     object
income              bool
dtype: object

## 5번 문제

adult dataframe의 workclass column을 ordinal encoder를 활용하여 encoding하시오.<br>
  **참조코드**
  ```python
  pandas.Series.to_numpy().reshape(-1, 1)
  
  df['column_name'].to_numpy().reshape(-1, 1)
  ```

## 5번 문제 답안

### 데이터 읽어오기

In [ ]:
import pandas as pd

adult_df = pd.read_csv('https://raw.githubusercontent.com/EugeneYoo/practice_file/main/adult.csv')

### 데이터 확인

In [ ]:
adult_df['workclass'].value_counts()

Index(['Private', 'Self-emp-not-inc', 'Local-gov', 'State-gov', 'Self-emp-inc',
       'Federal-gov', 'Without-pay', 'Never-worked'],
      dtype='object')

In [ ]:
# 상위 10개 확인
adult_df['workclass'].head(10)

0           State-gov
1    Self-emp-not-inc
2             Private
3             Private
4             Private
5             Private
6             Private
7    Self-emp-not-inc
8             Private
9             Private
Name: workclass, dtype: object

### Ordinal_encoder 적용

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
import numpy as np

# ordinal_encoder 객체 선언
ordinal_encoder = OrdinalEncoder()

# OrdinalEncoder 적용
class_cat_encoded = ordinal_encoder.fit_transform(adult_df['workclass'].to_numpy().reshape(-1, 1))
class_cat_encoded[:10]

array([[6.],
       [5.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [5.],
       [3.],
       [3.]])

### 참조 코드

oridinal encoder는 별도의 설정이 없을시, 알파뱃 순서대로 인코딩을 수행합니다.

별도의 설정을 통해 사용자 커스터마이징된 수치로 변환이 가능합니다.

어떤 숫자로 인코딩이 됐는지 편하게 확인하실 수 있도록 별도의 출력코드를 첨부합니다.

아래 결과랑 비교해보세요

```python
# 원래 값
0           State-gov
1    Self-emp-not-inc
2             Private
3             Private
4             Private
5             Private
6             Private
7    Self-emp-not-inc
8             Private
9             Private
Name: workclass, dtype: object

# 변환 값
array([[6.],
       [5.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [5.],
       [3.],
       [3.]])
```

In [ ]:
# workclass의 값을 별도로 저장함.
value = list(adult_df['workclass'].value_counts().keys())
# 이후 정렬 수행
value = sorted(value)

# key: 총 8개의 컬럼으로 0~7까지 사용
key = list(range(0,len(value)))

# 두 리스트를 기반으로 dict 생성
ordinal_encode = dict(zip(key, value))

# 각 매핑된 값 출력
print(ordinal_encode)

{0: 'Federal-gov', 1: 'Local-gov', 2: 'Never-worked', 3: 'Private', 4: 'Self-emp-inc', 5: 'Self-emp-not-inc', 6: 'State-gov', 7: 'Without-pay'}


## 6번 문제

adult_df의 workclass column을 one-hot encoder를 활용하여 encoding하시오.<br>
  **참조코드**
   ```python
  pandas.Series.to_numpy().reshape(-1, 1)
  
  df['column_name'].to_numpy().reshape(-1, 1)
  ```

## 6번 문제 답안

### 데이터 읽어오기

In [4]:
import pandas as pd

adult_df = pd.read_csv('https://raw.githubusercontent.com/EugeneYoo/practice_file/main/adult.csv')

### 데이터 확인

In [5]:
adult_df['workclass'].value_counts()

Private             22696
Self-emp-not-inc     2541
Local-gov            2093
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: workclass, dtype: int64

In [6]:
# 상위 10개 확인
adult_df['workclass'].head(10)

0           State-gov
1    Self-emp-not-inc
2             Private
3             Private
4             Private
5             Private
6             Private
7    Self-emp-not-inc
8             Private
9             Private
Name: workclass, dtype: object

### One-hot encoder 적용

In [7]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# OneHotEncoder 선언
onehot_encoder = OneHotEncoder()

# 변환 적용
class_cat_encoded = onehot_encoder.fit_transform(adult_df['workclass'].to_numpy().reshape(-1, 1))
print(class_cat_encoded.toarray()[:10])

[[0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [10]:
# 각 순서대로 원 핫 인코딩이 수행됨.
onehot_encoder.categories_

[array(['Federal-gov', 'Local-gov', 'Never-worked', 'Private',
        'Self-emp-inc', 'Self-emp-not-inc', 'State-gov', 'Without-pay',
        nan], dtype=object)]